= Keep it simple stupid

.2024-01-23 by Andreas Konrad

When I introduce myself I say: Hi, my name is Andreas Konrad, but people call me Konni.
I am the architect for the MARZIPAN product family.
And the most important architecture principle is: Keep it simple!

// People usually smile, some look like they want to laugh, some nod and some don't react at all.

It is, however, not simple at all to keep it simple.
In fact, it is very hard and constantly challenging.
It is not so much part of the science, engineering or craftsmanship aspects of architecture as it is an art.
This is why I dedicate this whole article to keeping it simple.

So, what's so hard about keeping it simple?

.Well, first off, people have a different understanding of simple.
What one might call simple, another might call complicated or complex.
This is because you can aim at simplifying different aspects.

* parameterize vs duplication
* redundancy vs more logic
* many simple things vs one complicated thing

.Second, it is hard to constantly work on simplifying things.

* E.g. passing all the detailed information is much easier than evaluating and reducing it to the minimal amount of necessary information
* E.g. just implementing something the way that comes natural to you is much easier than to think long and hard about how to make the solution simpler


So, how can you keep it simple?


